# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sidechain_types.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sidechain_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15sidechain_types.proto\x12\x08tari.rpc\x1a\x0btypes.proto\"\xf6\x01\n\x10SideChainFeature\x12J\n\x1bvalidator_node_registration\x18\x01 \x01(\x0b\x32#.tari.rpc.ValidatorNodeRegistrationH\x00\x12?\n\x15template_registration\x18\x02 \x01(\x0b\x32\x1e.tari.rpc.TemplateRegistrationH\x00\x12?\n\x13\x63onfidential_output\x18\x03 \x01(\x0b\x32 .tari.rpc.ConfidentialOutputDataH\x00\x42\x14\n\x12side_chain_feature\"W\n\x19ValidatorNodeRegistration\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12&\n\tsignature\x18\x02 \x01(\x0b\x32\x13.tari.rpc.Signature\"\x91\x02\n\x14TemplateRegistration\x12\x19\n\x11\x61uthor_public_key\x18\x01 \x01(\x0c\x12-\n\x10\x61uthor_signature\x18\x02 \x01(\x0b\x32\x13.tari.rpc.Signature\x12\x15\n\rtemplate_name\x18\x03 \x01(\t\x12\x18\n\x10template_version\x18\x04 \x01(\r\x12-\n\rtemplate_type\x18\x05 \x01(\x0b\x32\x16.tari.rpc.TemplateType\x12\'\n\nbuild_info\x18\x06 \x01(\x0b\x32\x13.tari.rpc.BuildInfo\x12\x12\n\nbinary_sha\x18\x07 \x01(\x0c\x12\x12\n\nbinary_url\x18\x08 \x01(\t\"2\n\x16\x43onfidentialOutputData\x12\x18\n\x10\x63laim_public_key\x18\x01 \x01(\x0c\"\x93\x01\n\x0cTemplateType\x12\"\n\x04wasm\x18\x01 \x01(\x0b\x32\x12.tari.rpc.WasmInfoH\x00\x12\"\n\x04\x66low\x18\x02 \x01(\x0b\x32\x12.tari.rpc.FlowInfoH\x00\x12*\n\x08manifest\x18\x03 \x01(\x0b\x32\x16.tari.rpc.ManifestInfoH\x00\x42\x0f\n\rtemplate_type\"\x1f\n\x08WasmInfo\x12\x13\n\x0b\x61\x62i_version\x18\x01 \x01(\r\"\n\n\x08\x46lowInfo\"\x0e\n\x0cManifestInfo\"2\n\tBuildInfo\x12\x10\n\x08repo_url\x18\x01 \x01(\t\x12\x13\n\x0b\x63ommit_hash\x18\x02 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sidechain_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIDECHAINFEATURE']._serialized_start=49
  _globals['_SIDECHAINFEATURE']._serialized_end=295
  _globals['_VALIDATORNODEREGISTRATION']._serialized_start=297
  _globals['_VALIDATORNODEREGISTRATION']._serialized_end=384
  _globals['_TEMPLATEREGISTRATION']._serialized_start=387
  _globals['_TEMPLATEREGISTRATION']._serialized_end=660
  _globals['_CONFIDENTIALOUTPUTDATA']._serialized_start=662
  _globals['_CONFIDENTIALOUTPUTDATA']._serialized_end=712
  _globals['_TEMPLATETYPE']._serialized_start=715
  _globals['_TEMPLATETYPE']._serialized_end=862
  _globals['_WASMINFO']._serialized_start=864
  _globals['_WASMINFO']._serialized_end=895
  _globals['_FLOWINFO']._serialized_start=897
  _globals['_FLOWINFO']._serialized_end=907
  _globals['_MANIFESTINFO']._serialized_start=909
  _globals['_MANIFESTINFO']._serialized_end=923
  _globals['_BUILDINFO']._serialized_start=925
  _globals['_BUILDINFO']._serialized_end=975
# @@protoc_insertion_point(module_scope)
