# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import network_pb2 as network__pb2
import transaction_pb2 as transaction__pb2
import validator_node_pb2 as validator__node__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in validator_node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ValidatorNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIdentity = channel.unary_unary(
                '/tari.rpc.ValidatorNode/GetIdentity',
                request_serializer=network__pb2.GetIdentityRequest.SerializeToString,
                response_deserializer=network__pb2.GetIdentityResponse.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/tari.rpc.ValidatorNode/GetMetadata',
                request_serializer=validator__node__pb2.GetMetadataRequest.SerializeToString,
                response_deserializer=validator__node__pb2.GetMetadataResponse.FromString,
                _registered_method=True)
        self.GetTokenData = channel.unary_unary(
                '/tari.rpc.ValidatorNode/GetTokenData',
                request_serializer=validator__node__pb2.GetTokenDataRequest.SerializeToString,
                response_deserializer=validator__node__pb2.GetTokenDataResponse.FromString,
                _registered_method=True)
        self.InvokeReadMethod = channel.unary_unary(
                '/tari.rpc.ValidatorNode/InvokeReadMethod',
                request_serializer=validator__node__pb2.InvokeReadMethodRequest.SerializeToString,
                response_deserializer=validator__node__pb2.InvokeReadMethodResponse.FromString,
                _registered_method=True)
        self.InvokeMethod = channel.unary_unary(
                '/tari.rpc.ValidatorNode/InvokeMethod',
                request_serializer=validator__node__pb2.InvokeMethodRequest.SerializeToString,
                response_deserializer=validator__node__pb2.InvokeMethodResponse.FromString,
                _registered_method=True)
        self.GetConstitutionRequests = channel.unary_stream(
                '/tari.rpc.ValidatorNode/GetConstitutionRequests',
                request_serializer=validator__node__pb2.GetConstitutionRequestsRequest.SerializeToString,
                response_deserializer=transaction__pb2.TransactionOutput.FromString,
                _registered_method=True)
        self.PublishContractAcceptance = channel.unary_unary(
                '/tari.rpc.ValidatorNode/PublishContractAcceptance',
                request_serializer=validator__node__pb2.PublishContractAcceptanceRequest.SerializeToString,
                response_deserializer=validator__node__pb2.PublishContractAcceptanceResponse.FromString,
                _registered_method=True)
        self.PublishContractUpdateProposalAcceptance = channel.unary_unary(
                '/tari.rpc.ValidatorNode/PublishContractUpdateProposalAcceptance',
                request_serializer=validator__node__pb2.PublishContractUpdateProposalAcceptanceRequest.SerializeToString,
                response_deserializer=validator__node__pb2.PublishContractUpdateProposalAcceptanceResponse.FromString,
                _registered_method=True)


class ValidatorNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIdentity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTokenData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeReadMethod(self, request, context):
        """rpc ExecuteInstruction(ExecuteInstructionRequest) returns (ExecuteInstructionResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConstitutionRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishContractAcceptance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishContractUpdateProposalAcceptance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidatorNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentity,
                    request_deserializer=network__pb2.GetIdentityRequest.FromString,
                    response_serializer=network__pb2.GetIdentityResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=validator__node__pb2.GetMetadataRequest.FromString,
                    response_serializer=validator__node__pb2.GetMetadataResponse.SerializeToString,
            ),
            'GetTokenData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenData,
                    request_deserializer=validator__node__pb2.GetTokenDataRequest.FromString,
                    response_serializer=validator__node__pb2.GetTokenDataResponse.SerializeToString,
            ),
            'InvokeReadMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeReadMethod,
                    request_deserializer=validator__node__pb2.InvokeReadMethodRequest.FromString,
                    response_serializer=validator__node__pb2.InvokeReadMethodResponse.SerializeToString,
            ),
            'InvokeMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeMethod,
                    request_deserializer=validator__node__pb2.InvokeMethodRequest.FromString,
                    response_serializer=validator__node__pb2.InvokeMethodResponse.SerializeToString,
            ),
            'GetConstitutionRequests': grpc.unary_stream_rpc_method_handler(
                    servicer.GetConstitutionRequests,
                    request_deserializer=validator__node__pb2.GetConstitutionRequestsRequest.FromString,
                    response_serializer=transaction__pb2.TransactionOutput.SerializeToString,
            ),
            'PublishContractAcceptance': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishContractAcceptance,
                    request_deserializer=validator__node__pb2.PublishContractAcceptanceRequest.FromString,
                    response_serializer=validator__node__pb2.PublishContractAcceptanceResponse.SerializeToString,
            ),
            'PublishContractUpdateProposalAcceptance': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishContractUpdateProposalAcceptance,
                    request_deserializer=validator__node__pb2.PublishContractUpdateProposalAcceptanceRequest.FromString,
                    response_serializer=validator__node__pb2.PublishContractUpdateProposalAcceptanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tari.rpc.ValidatorNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tari.rpc.ValidatorNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ValidatorNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.ValidatorNode/GetIdentity',
            network__pb2.GetIdentityRequest.SerializeToString,
            network__pb2.GetIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.ValidatorNode/GetMetadata',
            validator__node__pb2.GetMetadataRequest.SerializeToString,
            validator__node__pb2.GetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTokenData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.ValidatorNode/GetTokenData',
            validator__node__pb2.GetTokenDataRequest.SerializeToString,
            validator__node__pb2.GetTokenDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeReadMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.ValidatorNode/InvokeReadMethod',
            validator__node__pb2.InvokeReadMethodRequest.SerializeToString,
            validator__node__pb2.InvokeReadMethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.ValidatorNode/InvokeMethod',
            validator__node__pb2.InvokeMethodRequest.SerializeToString,
            validator__node__pb2.InvokeMethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConstitutionRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tari.rpc.ValidatorNode/GetConstitutionRequests',
            validator__node__pb2.GetConstitutionRequestsRequest.SerializeToString,
            transaction__pb2.TransactionOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishContractAcceptance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.ValidatorNode/PublishContractAcceptance',
            validator__node__pb2.PublishContractAcceptanceRequest.SerializeToString,
            validator__node__pb2.PublishContractAcceptanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishContractUpdateProposalAcceptance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.ValidatorNode/PublishContractUpdateProposalAcceptance',
            validator__node__pb2.PublishContractUpdateProposalAcceptanceRequest.SerializeToString,
            validator__node__pb2.PublishContractUpdateProposalAcceptanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
