# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import network_pb2 as network__pb2
import types_pb2 as types__pb2
import wallet_pb2 as wallet__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in wallet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WalletStub(object):
    """The gRPC interface for interacting with the wallet.
    Returns the current version of the running wallet service.

    This method retrieves the semantic version of the wallet software as defined in the Cargo.toml file (e.g., "1.2.3"). Useful for diagnostics and compatibility checks.

    Example usage (JavaScript gRPC client):
    ```javascript
    const response = await client.getVersion({});
    console.log(response.version); // e.g., "1.2.3"
    ```

    Example response:
    ```json
    {
    "version": "1.2.3"
    }
    ```
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVersion = channel.unary_unary(
                '/tari.rpc.Wallet/GetVersion',
                request_serializer=wallet__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=wallet__pb2.GetVersionResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/tari.rpc.Wallet/GetState',
                request_serializer=wallet__pb2.GetStateRequest.SerializeToString,
                response_deserializer=wallet__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.CheckConnectivity = channel.unary_unary(
                '/tari.rpc.Wallet/CheckConnectivity',
                request_serializer=wallet__pb2.GetConnectivityRequest.SerializeToString,
                response_deserializer=wallet__pb2.CheckConnectivityResponse.FromString,
                _registered_method=True)
        self.CheckForUpdates = channel.unary_unary(
                '/tari.rpc.Wallet/CheckForUpdates',
                request_serializer=types__pb2.Empty.SerializeToString,
                response_deserializer=network__pb2.SoftwareUpdate.FromString,
                _registered_method=True)
        self.Identify = channel.unary_unary(
                '/tari.rpc.Wallet/Identify',
                request_serializer=network__pb2.GetIdentityRequest.SerializeToString,
                response_deserializer=network__pb2.GetIdentityResponse.FromString,
                _registered_method=True)
        self.GetAddress = channel.unary_unary(
                '/tari.rpc.Wallet/GetAddress',
                request_serializer=types__pb2.Empty.SerializeToString,
                response_deserializer=wallet__pb2.GetAddressResponse.FromString,
                _registered_method=True)
        self.GetPaymentIdAddress = channel.unary_unary(
                '/tari.rpc.Wallet/GetPaymentIdAddress',
                request_serializer=wallet__pb2.GetPaymentIdAddressRequest.SerializeToString,
                response_deserializer=wallet__pb2.GetCompleteAddressResponse.FromString,
                _registered_method=True)
        self.GetCompleteAddress = channel.unary_unary(
                '/tari.rpc.Wallet/GetCompleteAddress',
                request_serializer=types__pb2.Empty.SerializeToString,
                response_deserializer=wallet__pb2.GetCompleteAddressResponse.FromString,
                _registered_method=True)
        self.Transfer = channel.unary_unary(
                '/tari.rpc.Wallet/Transfer',
                request_serializer=wallet__pb2.TransferRequest.SerializeToString,
                response_deserializer=wallet__pb2.TransferResponse.FromString,
                _registered_method=True)
        self.GetTransactionInfo = channel.unary_unary(
                '/tari.rpc.Wallet/GetTransactionInfo',
                request_serializer=wallet__pb2.GetTransactionInfoRequest.SerializeToString,
                response_deserializer=wallet__pb2.GetTransactionInfoResponse.FromString,
                _registered_method=True)
        self.GetCompletedTransactions = channel.unary_stream(
                '/tari.rpc.Wallet/GetCompletedTransactions',
                request_serializer=wallet__pb2.GetCompletedTransactionsRequest.SerializeToString,
                response_deserializer=wallet__pb2.GetCompletedTransactionsResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/tari.rpc.Wallet/GetBalance',
                request_serializer=wallet__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=wallet__pb2.GetBalanceResponse.FromString,
                _registered_method=True)
        self.GetUnspentAmounts = channel.unary_unary(
                '/tari.rpc.Wallet/GetUnspentAmounts',
                request_serializer=types__pb2.Empty.SerializeToString,
                response_deserializer=wallet__pb2.GetUnspentAmountsResponse.FromString,
                _registered_method=True)
        self.CoinSplit = channel.unary_unary(
                '/tari.rpc.Wallet/CoinSplit',
                request_serializer=wallet__pb2.CoinSplitRequest.SerializeToString,
                response_deserializer=wallet__pb2.CoinSplitResponse.FromString,
                _registered_method=True)
        self.ImportUtxos = channel.unary_unary(
                '/tari.rpc.Wallet/ImportUtxos',
                request_serializer=wallet__pb2.ImportUtxosRequest.SerializeToString,
                response_deserializer=wallet__pb2.ImportUtxosResponse.FromString,
                _registered_method=True)
        self.GetNetworkStatus = channel.unary_unary(
                '/tari.rpc.Wallet/GetNetworkStatus',
                request_serializer=types__pb2.Empty.SerializeToString,
                response_deserializer=network__pb2.NetworkStatusResponse.FromString,
                _registered_method=True)
        self.ListConnectedPeers = channel.unary_unary(
                '/tari.rpc.Wallet/ListConnectedPeers',
                request_serializer=types__pb2.Empty.SerializeToString,
                response_deserializer=network__pb2.ListConnectedPeersResponse.FromString,
                _registered_method=True)
        self.CancelTransaction = channel.unary_unary(
                '/tari.rpc.Wallet/CancelTransaction',
                request_serializer=wallet__pb2.CancelTransactionRequest.SerializeToString,
                response_deserializer=wallet__pb2.CancelTransactionResponse.FromString,
                _registered_method=True)
        self.RevalidateAllTransactions = channel.unary_unary(
                '/tari.rpc.Wallet/RevalidateAllTransactions',
                request_serializer=wallet__pb2.RevalidateRequest.SerializeToString,
                response_deserializer=wallet__pb2.RevalidateResponse.FromString,
                _registered_method=True)
        self.ValidateAllTransactions = channel.unary_unary(
                '/tari.rpc.Wallet/ValidateAllTransactions',
                request_serializer=wallet__pb2.ValidateRequest.SerializeToString,
                response_deserializer=wallet__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.SendShaAtomicSwapTransaction = channel.unary_unary(
                '/tari.rpc.Wallet/SendShaAtomicSwapTransaction',
                request_serializer=wallet__pb2.SendShaAtomicSwapRequest.SerializeToString,
                response_deserializer=wallet__pb2.SendShaAtomicSwapResponse.FromString,
                _registered_method=True)
        self.CreateBurnTransaction = channel.unary_unary(
                '/tari.rpc.Wallet/CreateBurnTransaction',
                request_serializer=wallet__pb2.CreateBurnTransactionRequest.SerializeToString,
                response_deserializer=wallet__pb2.CreateBurnTransactionResponse.FromString,
                _registered_method=True)
        self.ClaimShaAtomicSwapTransaction = channel.unary_unary(
                '/tari.rpc.Wallet/ClaimShaAtomicSwapTransaction',
                request_serializer=wallet__pb2.ClaimShaAtomicSwapRequest.SerializeToString,
                response_deserializer=wallet__pb2.ClaimShaAtomicSwapResponse.FromString,
                _registered_method=True)
        self.ClaimHtlcRefundTransaction = channel.unary_unary(
                '/tari.rpc.Wallet/ClaimHtlcRefundTransaction',
                request_serializer=wallet__pb2.ClaimHtlcRefundRequest.SerializeToString,
                response_deserializer=wallet__pb2.ClaimHtlcRefundResponse.FromString,
                _registered_method=True)
        self.CreateTemplateRegistration = channel.unary_unary(
                '/tari.rpc.Wallet/CreateTemplateRegistration',
                request_serializer=wallet__pb2.CreateTemplateRegistrationRequest.SerializeToString,
                response_deserializer=wallet__pb2.CreateTemplateRegistrationResponse.FromString,
                _registered_method=True)
        self.SetBaseNode = channel.unary_unary(
                '/tari.rpc.Wallet/SetBaseNode',
                request_serializer=wallet__pb2.SetBaseNodeRequest.SerializeToString,
                response_deserializer=wallet__pb2.SetBaseNodeResponse.FromString,
                _registered_method=True)
        self.StreamTransactionEvents = channel.unary_stream(
                '/tari.rpc.Wallet/StreamTransactionEvents',
                request_serializer=wallet__pb2.TransactionEventRequest.SerializeToString,
                response_deserializer=wallet__pb2.TransactionEventResponse.FromString,
                _registered_method=True)
        self.RegisterValidatorNode = channel.unary_unary(
                '/tari.rpc.Wallet/RegisterValidatorNode',
                request_serializer=wallet__pb2.RegisterValidatorNodeRequest.SerializeToString,
                response_deserializer=wallet__pb2.RegisterValidatorNodeResponse.FromString,
                _registered_method=True)


class WalletServicer(object):
    """The gRPC interface for interacting with the wallet.
    Returns the current version of the running wallet service.

    This method retrieves the semantic version of the wallet software as defined in the Cargo.toml file (e.g., "1.2.3"). Useful for diagnostics and compatibility checks.

    Example usage (JavaScript gRPC client):
    ```javascript
    const response = await client.getVersion({});
    console.log(response.version); // e.g., "1.2.3"
    ```

    Example response:
    ```json
    {
    "version": "1.2.3"
    }
    ```
    """

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Returns the current operational state of the wallet.

        This RPC provides an overview of the wallet's internal status, including:
        - The latest blockchain height scanned by the wallet
        - The current balance (available, pending incoming/outgoing)
        - Network connectivity status with the base node

        This is commonly used by UI clients or backend systems to confirm the wallet is healthy,
        synchronized, and connected to the Tari network.

        Example usage (JavaScript):
        ```javascript
        const response = await client.getState({});
        console.log(response.scanned_height); // e.g., 1523493
        console.log(response.balance.available_balance); // e.g., 1234567890
        console.log(response.network.status); // e.g., "Online"
        ```

        Example response:
        ```json
        {
        "scanned_height": 1523493,
        "balance": {
        "available_balance": 1234567890,
        "pending_incoming_balance": 100000000,
        "pending_outgoing_balance": 0
        },
        "network": {
        "status": "Online",
        "avg_latency_ms": 28,
        "num_node_connections": 8
        }
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckConnectivity(self, request, context):
        """This RPC returns a lightweight response indicating whether the wallet is connected to the network, attempting to connect, or currently offline. This is useful for UIs or clients to determine if network interactions like transactions or syncs are possible.

        Example usage (JavaScript):
        ```javascript
        const response = await client.checkConnectivity({});
        console.log(response.status); // e.g., 1 (Online)
        ```

        Example response:
        ```json
        {
        "status": "Online"
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckForUpdates(self, request, context):
        """Check for new updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Identify(self, request, context):
        """The `Identify` RPC call returns the identity information of the wallet node.
        This includes:
        - **Public Key**: The wallet’s cryptographic public key.
        - **Public Address**: The wallet’s public address used to receive funds.
        - **Node ID**: The unique identifier of the wallet node in the network.

        Example usage (JavaScript):
        ```javascript
        // Call the Identify RPC method
        client.Identify({}, (error, response) => {
        if (error) {
        console.error('Error:', error);
        } else {
        console.log('Identity Response:', response);
        }
        });
        ```

        **Sample JSON Response:**

        ```json
        {
        "public_key": "0x04b2c5f3fe65bb1c3cde019e34f3eab1234598c820dca43bbf4d5686a980ddc69e0d4b180d85990d0a5e4aee46e0a6ad9283f0a41783992a70c548e53e47321fa",
        "public_address": "14HVCEeZC2RGE4SDn3yGwqzXepJ2LDqXva7kb4fherYMQR9dF7341T3TjMZobB1a6xouGvS5SXwEvXKwK3zLz2rgReh",
        "node_id": "0x1234abcd5678efgh9012ijkl3456mnop"
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddress(self, request, context):
        """This RPC returns two types of wallet addresses: interactive and one-sided addresses.
        It provides these addresses in byte format as part of the response.
        - **Interactive Address**: This is a type of address used for interaction and communication with the wallet.
        - **One-Sided Address**: This is another address type, typically used in scenarios where a one-way interaction or transaction is needed.

        Example usage (JavaScript):
        // Call the GetAddress RPC method
        client.GetAddress({}, (error, response) => {
        if (error) {
        console.error('Error:', error);
        } else {
        console.log('Address Response:', response);
        }
        });
        ```

        **Sample JSON Response:**
        // ```json
        {
        "interactive_address": "0x14b27bde3f7d9c9d7455f16b056a3c439c663af93356f56e16d2b2c79e6995c44c9c6c7c",
        "one_sided_address": "0x12b35ddcb2270a72d7b327abc7cd4f607a492c6e13e72e65c34742069e48bd3bc462df63"
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaymentIdAddress(self, request, context):
        """This RPC returns addresses generated for a specific payment ID. It provides both the interactive 
        and one-sided addresses for the given payment ID, along with their respective representations in 
        base58 and emoji formats.

        Example usage (JavaScript):

        ```javascript
        // Prepare the payment ID for the request
        const paymentId = Buffer.from('your_payment_id_here', 'hex');
        const request = { payment_id: paymentId };

        // Call the GetPaymentIdAddress RPC method
        client.GetPaymentIdAddress(request, (error, response) => {
        if (error) {
        console.error('Error:', error);
        } else {
        console.log('Payment ID Address Response:', response);
        }
        });
        ```

        **Sample JSON Response:**

        ```json
        {
        "interactive_address": "0411aabbccddeeff00112233445566778899aabbccddeeff0011223344556677",
        "one_sided_address": "02ff8899aabbccddeeff00112233445566778899aabbccddeeff001122334455",
        "interactive_address_base58": "14HVCEeZC2RGE4SDn3yG.....6xouGvS5SXwEvXKwK3zLz2rgReh",
        "one_sided_address_base58": "12HVCEeZC2RGE4SDn3yGwqz.....obB1a6xouGvS5SXwEvXKwK3zLz2rgReL",
        "interactive_address_emoji": "🐢🌊💤🔌🚑🐛🏦⚽🍓🐭🚁🎢🔪🥐👛🍞.....🍐🍟💵🎉🍯🎁🎾🎼💻💄🍳🍐🤔🥝🍫👅🚀🐬🎭",
        "one_sided_address_emoji": "🐢📟💤🔌🚑🐛🏦⚽🍓🐭🚁🎢🔪🥐👛🍞📜.....🍐🍟💵🎉🍯🎁🎾🎼💻💄🍳🍐🤔🥝🍫👅🚀🐬🎭"
        }
        ```

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompleteAddress(self, request, context):
        """This RPC call that retrieves the current wallet's interactive and one-sided addresses in multiple formats and returns them in a structured response.
        The response includes:
        - Raw binary
        - Base58-encoded (human-readable)
        - Emoji-encoded (for fun and friendliness)

        Example usage (JavaScript with gRPC):

        ```js
        const client = new WalletClient('localhost:50051', grpc.credentials.createInsecure());
        client.getCompleteAddress({}, (err, response) => {
        if (err) console.error(err);
        else console.log(response);
        });
        ```

        Sample response:
        ```json
        {
        "interactive_address": "0411aabbccddeeff00112233445566778899aabbccddeeff0011223344556677",
        "one_sided_address": "02ff8899aabbccddeeff00112233445566778899aabbccddeeff001122334455",
        "interactive_address_base58": "14HVCEeZC2RGE4SDn3yG.....6xouGvS5SXwEvXKwK3zLz2rgReh",
        "one_sided_address_base58": "12HVCEeZC2RGE4SDn3yGwqz.....obB1a6xouGvS5SXwEvXKwK3zLz2rgReL",
        "interactive_address_emoji": "🐢🌊💤🔌🚑🐛🏦⚽🍓🐭🚁🎢🔪🥐👛🍞.....🍐🍟💵🎉🍯🎁🎾🎼💻💄🍳🍐🤔🥝🍫👅🚀🐬🎭",
        "one_sided_address_emoji": "🐢📟💤🔌🚑🐛🏦⚽🍓🐭🚁🎢🔪🥐👛🍞📜.....🍐🍟💵🎉🍯🎁🎾🎼💻💄🍳🍐🤔🥝🍫👅🚀🐬🎭"
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transfer(self, request, context):
        """This call supports standard interactive transactions (Mimblewimble),
        one-sided transactions, and one-sided-to-stealth-address transactions.
        Each recipient must include a valid Tari address, amount, fee, and payment type.

        ### Example JavaScript gRPC client usage:

        ```javascript
        const recipient = new PaymentRecipient();
        recipient.setAddress("14HVCEeZ...");
        recipient.setAmount(1000000); // 1 T
        recipient.setFeePerGram(25);
        recipient.setPaymentType(PaymentType.ONE_SIDED);
        recipient.setPaymentId(Buffer.from("abc123", "utf-8"));

        const request = new TransferRequest();
        request.setRecipientsList([recipient]);

        client.transfer(request, (err, response) => {
        if (err) console.error(err);
        else console.log(response.toObject());
        });
        ```

        ### Sample JSON Response:

        ```json
        {
        "results": [
        {
        "address": "14HVCEeZ...",
        "transaction_id": 12345,
        "is_success": true,
        "failure_message": ""
        }
        ]
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionInfo(self, request, context):
        """Returns the transaction details for the given transaction IDs.

        The GetTransactionInfo RPC retrieves detailed information about specific transactions based on their IDs.
        The response includes details such as transaction status, direction, amount, fee, and more.

        ### Request Parameters:

        - `transaction_ids` (required):  
        - **Type**: `repeated uint64`  
        - **Description**: A list of transaction IDs to query.  
        - **Restrictions**:  
        - Must contain at least one ID.
        - All IDs must be valid unsigned 64-bit integers.
        - Duplicates will be ignored; only the first occurrence is processed.
        - If a transaction ID is not found, it will be returned with a `status` of `NOT_FOUND`.

        ### Example JavaScript gRPC client usage:

        ```javascript
        const request = { transaction_ids: [12345, 67890] };
        client.getTransactionInfo(request, (err, response) => {
        if (err) console.error(err);
        else console.log(response.transactions);
        });
        ```

        ### Sample JSON Response:

        ```json
        {
        "transactions": [
        {
        "tx_id": 12345,
        "source_address": "0x1234abcd...",
        "dest_address": "0x5678efgh...",
        "status": "TRANSACTION_STATUS_MINED_CONFIRMED",
        "direction": "TRANSACTION_DIRECTION_OUTBOUND",
        "amount": 1000000,
        "fee": 25,
        "is_cancelled": false,
        "excess_sig": "0xabcdef...",
        "timestamp": 1681234567,
        "payment_id": "0xdeadbeef...",
        "mined_in_block_height": 1523493
        }
        ]
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompletedTransactions(self, request, context):
        """Streams completed transactions for a given user payment ID.

        The `GetCompletedTransactions` call retrieves all completed wallet transactions,
        optionally filtered by a specific `payment_id` and/or block hash. The response is streamed back to the client
        one transaction at a time, with each transaction including details such as status, direction,
        amount, fees, and associated metadata.

        ### Request Parameters:

        - `payment_id` (optional):
        - **Type**: `UserPaymentId` (a flexible ID object)
        - **Description**: Allows filtering the completed transactions by a specific payment ID.
        - **Accepted Formats** (must provide **only one**):
        - `u256`: a 32-byte hexadecimal string.
        - `utf8_string`: a UTF-8 string.
        - `user_bytes`: raw bytes.
        - **Restrictions**:
        - Exactly **one format must be set**. Providing more than one or none results in an error.
        - If no `payment_id` is provided, all completed transactions will be returned.

        - `block_hash` (optional):
        - **Type**: `string`
        - **Description**: A specific block hash to filter transactions by.
        - **Accepted Formats**
        - Hexadecimal string representing the block hash.
        - **Restrictions**:
        - If provided, the transactions will be filtered to only those included in the specified block.

        - `block_height` (optional):
        - **Type**: `uint64`
        - **Description**: A specific block height to filter transactions by.
        - **Restrictions**:
        - If provided, the transactions will be filtered to only those included in the specified height.


        ### Example JavaScript gRPC client usage:

        ```javascript
        const request = {
        payment_id: {
        utf8_string: "invoice-001"
        }
        };
        const call = client.getCompletedTransactions(request);
        call.on('data', (response) => {
        console.log(response.transaction);
        });
        call.on('error', console.error);
        call.on('end', () => console.log("Stream ended"));
        ```

        ### Sample Streamed JSON Response:

        ```json
        {
        "transaction": {
        "tx_id": 12345,
        "source_address": "0x1234abcd...",
        "dest_address": "0x5678efgh...",
        "status": "TRANSACTION_STATUS_MINED_CONFIRMED",
        "direction": "TRANSACTION_DIRECTION_INBOUND",
        "amount": 500000,
        "fee": 20,
        "is_cancelled": false,
        "excess_sig": "0xabcdef...",
        "timestamp": 1681234567,
        "payment_id": "0xdeadbeef...",
        "mined_in_block_height": 1523493
        }
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Returns the wallet balance details.

        The `GetBalance` call retrieves the current balance status of the wallet,
        optionally filtered by a specific `payment_id`. The response includes detailed
        breakdowns of available, pending incoming/outgoing, and timelocked balances.

        ### Request Parameters:

        - `payment_id` (optional):
        - **Type**: `UserPaymentId` (one of several formats).
        - **Description**: An optional filter to retrieve the balance associated with a specific payment ID.
        - **Accepted Formats** (must provide **only one**):
        - `u256`: a 32-byte hexadecimal identifier.
        - `utf8_string`: a human-readable string ID.
        - `user_bytes`: raw binary bytes.
        - **Restrictions**:
        - Only one format must be provided at a time.
        - If multiple or no formats are provided within `payment_id`, the request will return an error.
        - If `payment_id` is omitted, the total wallet balance is returned.

        ### Example JavaScript gRPC client usage:

        ```javascript
        const request = {
        payment_id: {
        utf8_string: "invoice-002"
        }
        };
        client.getBalance(request, (err, response) => {
        if (err) console.error(err);
        else console.log("Balance:", response);
        });
        ```

        ### Sample JSON Response:

        ```json
        {
        "available_balance": 950000,
        "pending_incoming_balance": 200000,
        "pending_outgoing_balance": 50000,
        "timelocked_balance": 100000
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnspentAmounts(self, request, context):
        """Returns the total value of unspent outputs in the wallet.

        The `GetUnspentAmounts` call retrieves the sum of all unspent output amounts
        currently held by the wallet. These are outputs that have not yet been spent or time-locked,
        and are available for future transactions.

        ### Request Parameters:

        - *(none)*  
        - This method uses an empty request body (`google.protobuf.Empty`).
        - No filters or arguments are required.

        ### Example JavaScript gRPC client usage:

        ```javascript
        client.getUnspentAmounts({}, (err, response) => {
        if (err) console.error(err);
        else console.log("Total unspent amount:", response.amount);
        });
        ```

        ### Sample JSON Response:

        ```json
        {
        "amount": 1250000
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CoinSplit(self, request, context):
        """Creates a transaction that splits funds into multiple smaller outputs.

        The `CoinSplit` call initiates a transaction that divides wallet funds into several equal-sized outputs.
        This is useful for preparing a wallet for many small transactions (e.g., for micropayments or batching).
        The resulting transaction is broadcast and can be tracked via its transaction ID.

        ### Request Parameters:

        - `amount_per_split` (required):  
        - **Type**: `uint64`  
        - **Description**: The value of each individual output in the split.  
        - **Restrictions**: Must be greater than zero.

        - `split_count` (required):  
        - **Type**: `uint64`  
        - **Description**: The number of outputs to create.  
        - **Restrictions**: Must be greater than zero and within practical system limits.

        - `fee_per_gram` (required):  
        - **Type**: `uint64`  
        - **Description**: The transaction fee rate (per gram of weight).  
        - **Restrictions**: Should be set high enough to ensure confirmation.

        - `lock_height` (optional):  
        - **Type**: `uint64`  
        - **Description**: The earliest block height at which the transaction becomes valid.  
        - **Restrictions**: Defaults to 0 if not specified.

        - `payment_id` (optional):  
        - **Type**: `bytes`  
        - **Description**: A user-defined identifier for tracking or referencing the transaction.  
        - **Restrictions**: Optional; can be left empty.

        ### Example JavaScript gRPC client usage:

        ```javascript
        const request = {
        amount_per_split: 100000,
        split_count: 5,
        fee_per_gram: 25,
        lock_height: 0,
        payment_id: new Uint8Array([])
        };
        client.coinSplit(request, (err, response) => {
        if (err) console.error(err);
        else console.log("Created CoinSplit Tx ID:", response.tx_id);
        });
        ```

        ### Sample JSON Response:

        ```json
        {
        "tx_id": 987654321
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportUtxos(self, request, context):
        """Imports UTXOs into the wallet as spendable outputs.

        The `ImportUtxos` call allows you to manually insert one or more previously received UTXOs
        into the wallet, marking them as spendable without needing rewindable metadata.
        Each UTXO is associated with a transaction ID in the response.

        ### Request Parameters:

        - `outputs` (required):  
        - **Type**: `repeated UnblindedOutput`  
        - **Description**: A list of unblinded outputs to import into the wallet.  
        - **Restrictions**:  
        - Each output must be valid and convertible to an internal UTXO format.
        - The list must contain at least one item.

        - `payment_id` (optional):  
        - **Type**: `bytes`  
        - **Description**: An optional user-defined identifier to associate with the imported outputs.  
        - **Restrictions**:  
        - Can be left empty if not needed.
        - Must be a valid byte string if provided.

        ### Example JavaScript gRPC client usage:

        ```javascript
        const request = {
        outputs: [/* array of unblinded outputs */],
        payment_id: new Uint8Array([])
        };
        client.importUtxos(request, (err, response) => {
        if (err) console.error(err);
        else console.log("Imported Tx IDs:", response.tx_ids);
        });
        ```

        ### Sample JSON Response:

        ```json
        {
        "tx_ids": [101, 102, 103]
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworkStatus(self, request, context):
        """Returns the wallet's current network connectivity status.

        The `GetNetworkStatus` call provides a snapshot of the wallet’s connection to the Tari network,
        including whether it is online, the number of active peer connections, and the average latency
        to the configured base node.

        ### Request Parameters:

        - *(none)*  
        - This method uses an empty request body (`google.protobuf.Empty`).
        - No filters or arguments are required.

        ### Example JavaScript gRPC client usage:

        ```javascript
        client.getNetworkStatus({}, (err, response) => {
        if (err) console.error(err);
        else console.log("Network Status:", response);
        });
        ```

        ### Sample JSON Response:

        ```json
        {
        "status": "ONLINE",
        "avg_latency_ms": 142,
        "num_node_connections": 8
        }
        ```

        ### Status Field Values:

        The `status` field indicates the current network connectivity of the wallet. Possible values are:

        - `ONLINE`:  
        - The wallet is fully connected to the network and functioning normally.  
        - The node has enough active peer connections to operate efficiently.

        - `DEGRADED`:  
        - The wallet is connected to some peers but not enough to maintain full functionality.  
        - This could indicate issues with network connectivity, such as intermittent disconnections or insufficient peers, leading to reduced performance or reliability.

        - `OFFLINE`:  
        - The wallet is not connected to any peers.  
        - This status means the wallet is unable to communicate with the network and cannot perform any network-related operations.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConnectedPeers(self, request, context):
        """Returns a list of peers currently connected to the wallet.

        The `ListConnectedPeers` call retrieves information about peers that the wallet is currently
        connected to. This includes details such as peer addresses, connection status, supported protocols,
        and other metadata relevant to the connection.

        ### Request Parameters:

        - *(none)*  
        - This method uses an empty request body (`google.protobuf.Empty`).
        - No filters or arguments are required.

        ### Response Fields:

        - **connected_peers**: List of peers currently connected to the wallet.
        - **public_key**: The peer's public key (bytes).
        - **node_id**: The unique node ID of the peer (bytes).
        - **addresses**: List of the peer's addresses (repeated Address).
        - **last_connection**: The timestamp of the last connection attempt (uint64).
        - **flags**: Flags associated with the peer (uint32).
        - **banned_until**: The timestamp until which the peer is banned (uint64, 0 if not banned).
        - **banned_reason**: The reason for banning the peer (string, empty if not banned).
        - **offline_at**: The timestamp indicating when the peer went offline (uint64, 0 if online).
        - **features**: The features supported by the peer (uint32).
        - **supported_protocols**: List of supported protocols by the peer (repeated bytes).
        - **user_agent**: The user agent advertised by the peer (string).

        ### Example JavaScript gRPC client usage:

        ```javascript
        client.listConnectedPeers({}, (err, response) => {
        if (err) console.error(err);
        else console.log("Connected Peers:", response);
        });
        ```

        ### Sample JSON Response:

        ```json
        {
        "connected_peers": [
        {
        "public_key": "0x1234abcd...",
        "node_id": "0x5678efgh...",
        "addresses": [
        "127.0.0.1:18080",
        "192.168.1.2:18080"
        ],
        "last_connection": 1625493123,
        "flags": 1,
        "banned_until": 0,
        "banned_reason": "",
        "offline_at": 0,
        "features": 10,
        "supported_protocols": [
        "protocol_v1",
        "protocol_v2"
        ],
        "user_agent": "TariBaseNode/1.0.0"
        }
        ]
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTransaction(self, request, context):
        """Cancels a specific transaction by its ID.

        The `CancelTransaction` call allows a transaction to be cancelled by its unique transaction ID (TxId).
        If the cancellation is successful, the response will indicate success. Otherwise, the response will 
        contain a failure message with the reason for the failure.

        ### Request Parameters:

        - **tx_id**: The unique identifier for the transaction to be cancelled (uint64).

        ### Response Fields:

        - **is_success**: A boolean indicating whether the cancellation was successful (bool).
        - `true` if the cancellation was successful, `false` if not.
        - **failure_message**: A string that provides the reason for the failure, if applicable (string).
        - This field will be empty if the cancellation was successful.

        ### Example JavaScript gRPC client usage:

        ```javascript
        const request = { tx_id: 12345 };
        client.cancelTransaction(request, (err, response) => {
        if (err) console.error(err);
        else console.log(response);
        });
        ```

        ### Sample JSON Response:

        ```json
        {
        "is_success": true,
        "failure_message": ""
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevalidateAllTransactions(self, request, context):
        """Will trigger a complete revalidation of all wallet outputs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateAllTransactions(self, request, context):
        """Will trigger a validation of all wallet outputs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendShaAtomicSwapTransaction(self, request, context):
        """Sends a XTR SHA Atomic Swap transaction.

        The `SendShaAtomicSwapTransaction` call is used to initiate an Atomic Swap 
        transaction using SHA. It allows the sender to send a payment to the recipient 
        in exchange for an atomic swap, with SHA used as the secret for the swap.
        The method accepts the recipient's information and initiates the transaction.

        ### Request Parameters:
        - **recipient** (required): A PaymentRecipient object containing the recipient's address, 
        the amount to be swapped, the fee per gram, and the payment ID to identify the transaction.

        ### Response Fields:
        - **transaction_id**: The ID of the transaction.
        - **pre_image**: The SHA pre-image of the atomic swap.
        - **output_hash**: The hash of the output associated with the transaction.
        - **is_success**: Indicates whether the transaction was successful (true) or failed (false).
        - **failure_message**: Provides an error message if the transaction failed.

        ### Example JavaScript gRPC client usage:
        ```javascript
        const request = {
        recipient: {
        address: "t1abc12345",
        amount: 1000000,
        fee_per_gram: 10,
        payment_id: "0xdeadbeef"
        }
        };
        client.sendShaAtomicSwapTransaction(request, (err, response) => {
        if (err) console.error(err);
        else console.log(response);
        });
        ```

        ### Sample JSON Response:
        ```json
        {
        "transaction_id": 123456789,
        "pre_image": "0xabcdef1234567890",
        "output_hash": "0x123456abcdef7890",
        "is_success": true,
        "failure_message": ""
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBurnTransaction(self, request, context):
        """Creates a burn transaction for burning a specified amount of Tari currency.

        The `CreateBurnTransaction` call facilitates burning a certain amount of Tari
        by initiating a burn transaction. It allows the user to specify the amount to burn,
        along with a fee per gram and optionally a payment ID and claim public key.

        ### Request Parameters:
        - **amount** (required): The amount of Tari to be burned.
        - **fee_per_gram** (required): The fee per gram for the transaction.
        - **claim_public_key** (optional): The public key to claim ownership of the burned coins.
        - **payment_id** (optional): A unique identifier for the payment associated with the burn transaction.

        ### Response Fields:
        - **transaction_id**: The ID of the burn transaction.
        - **is_success**: Indicates whether the burn transaction was successfully created.
        - **failure_message**: Provides an error message if the transaction creation failed.
        - **commitment**: The commitment associated with the burn transaction.
        - **ownership_proof**: A proof of ownership for the burned coins.
        - **range_proof**: The range proof associated with the burned coins.
        - **reciprocal_claim_public_key**: The public key of the reciprocal claim for the burn.

        ### Example JavaScript gRPC client usage:
        ```javascript
        const request = {
        amount: 1000000,
        fee_per_gram: 10,
        claim_public_key: "0xabcdef1234567890",
        payment_id: "0xdeadbeef"
        };
        client.createBurnTransaction(request, (err, response) => {
        if (err) console.error(err);
        else console.log(response);
        });
        ```

        ### Sample JSON Response:
        ```json
        {
        "transaction_id": 123456789,
        "is_success": true,
        "failure_message": "",
        "commitment": "0xcommitmenthash",
        "ownership_proof": "0xownershipproof",
        "range_proof": "0xrangeproof",
        "reciprocal_claim_public_key": "0xreciprocalpublickey"
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimShaAtomicSwapTransaction(self, request, context):
        """Claims a SHA Atomic Swap transaction using a pre-image and output hash.

        The `ClaimShaAtomicSwapTransaction` call allows the user to unlock and claim funds from
        a hash-time-locked contract (HTLC) by supplying the correct pre-image that matches a
        previously committed SHA-256 hash. This pre-image proves the user’s knowledge of the
        secret required to spend the output.

        ### Request Parameters:
        - **output** (required): The hex-encoded output hash (SHA-256 digest) that was locked in the atomic swap.
        - **pre_image** (required): The hex-encoded original pre-image (raw bytes, *not* hashed) which, when hashed with SHA-256, must match the `output` hash.
        - **fee_per_gram** (required): The transaction fee per gram, specified as an unsigned integer.

        ### Input Validation:
        - `output` must be a valid hex-encoded SHA-256 hash (64 hex characters).
        - `pre_image` must be a valid hex string representing the original secret (any byte length, commonly 32 bytes).
        - `fee_per_gram` must be a non-zero `uint64`; a fee of `0` may be rejected or deprioritized by the network.

        ### Response Fields:
        - **results**: A `TransferResult` object containing transaction ID, success status, and an error message if applicable.

        ### Example JavaScript gRPC client usage:
        ```javascript
        const request = {
        output: "3e1f89af...e923", // SHA-256 hash of the expected pre-image
        pre_image: "6a1b2c...eaf1", // raw pre-image (not hashed)
        fee_per_gram: 10
        };
        client.claimShaAtomicSwapTransaction(request, (err, response) => {
        if (err) console.error(err);
        else console.log(response.results);
        });
        ```

        ### Sample JSON Response:
        ```json
        {
        "results": {
        "address": "",
        "transaction_id": 789654,
        "is_success": true,
        "failure_message": ""
        }
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimHtlcRefundTransaction(self, request, context):
        """Claims an HTLC refund transaction after the timelock period has passed.

        The `ClaimHtlcRefundTransaction` call enables the original sender of a Hash Time-Locked Contract (HTLC)
        to reclaim the locked funds if the recipient has not claimed them in time using the correct pre-image.
        This is possible only after the output's timelock has expired.

        ### Request Parameters:
        - **output_hash** (required): Hex-encoded SHA-256 hash of the HTLC output being refunded.
        - **fee_per_gram** (required): Transaction fee per gram, specified as a `uint64`.

        ### Input Validation:
        - `output_hash` must be a valid 64-character hex string representing the hash of the HTLC output.
        - `fee_per_gram` must be a non-zero `uint64` value.

        ### Response Fields:
        - **results**: A `TransferResult` object including transaction ID, success status, and failure reason if any.

        ### Example JavaScript gRPC client usage:
        ```javascript
        const request = {
        output_hash: "aabbccddeeff0011...99",
        fee_per_gram: 20
        };
        client.claimHtlcRefundTransaction(request, (err, response) => {
        if (err) console.error(err);
        else console.log(response.results);
        });
        ```

        ### Sample JSON Response:
        ```json
        {
        "results": {
        "address": "",
        "transaction_id": 889977,
        "is_success": true,
        "failure_message": ""
        }
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTemplateRegistration(self, request, context):
        """Creates a transaction with a template registration output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBaseNode(self, request, context):
        """The SetBaseNode call configures the base node peer for the wallet.

        This RPC sets the public key and network address of the base node peer that the wallet should communicate with.

        ### Request Fields:
        - `public_key_hex` (string): The public key of the base node, provided as a hex string.
        - `net_address` (string): The multiaddress of the base node (e.g., `/ip4/127.0.0.1/tcp/18141`).

        ### Example JavaScript gRPC client usage:

        ```javascript
        const request = {
        public_key_hex: "0281bdfc...",
        net_address: "/ip4/127.0.0.1/tcp/18141"
        };
        client.setBaseNode(request, (err, response) => {
        if (err) console.error(err);
        else console.log("Base node set successfully");
        });
        ```

        ### Sample JSON Request:
        ```json
        {
        "public_key_hex": "0281bdfc...",
        "net_address": "/ip4/127.0.0.1/tcp/18141"
        }
        ```

        ### Sample JSON Response:
        ```json
        {}
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTransactionEvents(self, request, context):
        """Streams real-time wallet transaction events to the client.

        The `StreamTransactionEvents` RPC provides a continuous stream of transaction events as they occur within the wallet.
        This allows clients to react to changes in transaction status such as received, sent, mined, or cancelled transactions,
        making it ideal for real-time UI updates or external monitoring.

        ### Request Parameters:
        - _(none)_ – This RPC does not take any parameters.

        ### Response Stream:
        - Each message in the response stream is a `TransactionEventResponse` containing:
        - **transaction**: A `TransactionEvent` object representing the latest event related to a wallet transaction.

        ### `TransactionEvent` Fields:
        - **event** (string): Human-readable event type. Examples include: `"Received"`, `"Mined"`, `"Cancelled"`, `"Sent"`.
        - **tx_id** (string): Transaction identifier.
        - **source_address** (bytes): Sender address, if applicable.
        - **dest_address** (bytes): Recipient address, if applicable.
        - **status** (string): Current status of the transaction. E.g., `"Completed"`, `"Pending"`, `"Cancelled"`.
        - **direction** (string): `"Inbound"` or `"Outbound"`.
        - **amount** (uint64): Transaction amount in microTari.
        - **payment_id** (bytes): Payment ID associated with the transaction.


        ### Example JavaScript gRPC client usage:
        ```javascript
        const call = client.streamTransactionEvents({});

        call.on("data", (response) => {
        console.log("Transaction Event:", response.transaction);
        });

        call.on("end", () => {
        console.log("Stream ended.");
        });

        call.on("error", (err) => {
        console.error("Stream error:", err);
        });
        ```

        ### Sample JSON Streamed Response:
        ```json
        {
        "transaction": {
        "event": "Mined",
        "tx_id": "103248",
        "source_address": "0xabc123...",
        "dest_address": "0xdef456...",
        "status": "Completed",
        "direction": "Outbound",
        "amount": 100000000,
        "payment_id": "0xdeadbeef..."
        }
        }
        ```
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterValidatorNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=wallet__pb2.GetVersionRequest.FromString,
                    response_serializer=wallet__pb2.GetVersionResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=wallet__pb2.GetStateRequest.FromString,
                    response_serializer=wallet__pb2.GetStateResponse.SerializeToString,
            ),
            'CheckConnectivity': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckConnectivity,
                    request_deserializer=wallet__pb2.GetConnectivityRequest.FromString,
                    response_serializer=wallet__pb2.CheckConnectivityResponse.SerializeToString,
            ),
            'CheckForUpdates': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckForUpdates,
                    request_deserializer=types__pb2.Empty.FromString,
                    response_serializer=network__pb2.SoftwareUpdate.SerializeToString,
            ),
            'Identify': grpc.unary_unary_rpc_method_handler(
                    servicer.Identify,
                    request_deserializer=network__pb2.GetIdentityRequest.FromString,
                    response_serializer=network__pb2.GetIdentityResponse.SerializeToString,
            ),
            'GetAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddress,
                    request_deserializer=types__pb2.Empty.FromString,
                    response_serializer=wallet__pb2.GetAddressResponse.SerializeToString,
            ),
            'GetPaymentIdAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaymentIdAddress,
                    request_deserializer=wallet__pb2.GetPaymentIdAddressRequest.FromString,
                    response_serializer=wallet__pb2.GetCompleteAddressResponse.SerializeToString,
            ),
            'GetCompleteAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompleteAddress,
                    request_deserializer=types__pb2.Empty.FromString,
                    response_serializer=wallet__pb2.GetCompleteAddressResponse.SerializeToString,
            ),
            'Transfer': grpc.unary_unary_rpc_method_handler(
                    servicer.Transfer,
                    request_deserializer=wallet__pb2.TransferRequest.FromString,
                    response_serializer=wallet__pb2.TransferResponse.SerializeToString,
            ),
            'GetTransactionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionInfo,
                    request_deserializer=wallet__pb2.GetTransactionInfoRequest.FromString,
                    response_serializer=wallet__pb2.GetTransactionInfoResponse.SerializeToString,
            ),
            'GetCompletedTransactions': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCompletedTransactions,
                    request_deserializer=wallet__pb2.GetCompletedTransactionsRequest.FromString,
                    response_serializer=wallet__pb2.GetCompletedTransactionsResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=wallet__pb2.GetBalanceRequest.FromString,
                    response_serializer=wallet__pb2.GetBalanceResponse.SerializeToString,
            ),
            'GetUnspentAmounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnspentAmounts,
                    request_deserializer=types__pb2.Empty.FromString,
                    response_serializer=wallet__pb2.GetUnspentAmountsResponse.SerializeToString,
            ),
            'CoinSplit': grpc.unary_unary_rpc_method_handler(
                    servicer.CoinSplit,
                    request_deserializer=wallet__pb2.CoinSplitRequest.FromString,
                    response_serializer=wallet__pb2.CoinSplitResponse.SerializeToString,
            ),
            'ImportUtxos': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportUtxos,
                    request_deserializer=wallet__pb2.ImportUtxosRequest.FromString,
                    response_serializer=wallet__pb2.ImportUtxosResponse.SerializeToString,
            ),
            'GetNetworkStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkStatus,
                    request_deserializer=types__pb2.Empty.FromString,
                    response_serializer=network__pb2.NetworkStatusResponse.SerializeToString,
            ),
            'ListConnectedPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConnectedPeers,
                    request_deserializer=types__pb2.Empty.FromString,
                    response_serializer=network__pb2.ListConnectedPeersResponse.SerializeToString,
            ),
            'CancelTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTransaction,
                    request_deserializer=wallet__pb2.CancelTransactionRequest.FromString,
                    response_serializer=wallet__pb2.CancelTransactionResponse.SerializeToString,
            ),
            'RevalidateAllTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.RevalidateAllTransactions,
                    request_deserializer=wallet__pb2.RevalidateRequest.FromString,
                    response_serializer=wallet__pb2.RevalidateResponse.SerializeToString,
            ),
            'ValidateAllTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAllTransactions,
                    request_deserializer=wallet__pb2.ValidateRequest.FromString,
                    response_serializer=wallet__pb2.ValidateResponse.SerializeToString,
            ),
            'SendShaAtomicSwapTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendShaAtomicSwapTransaction,
                    request_deserializer=wallet__pb2.SendShaAtomicSwapRequest.FromString,
                    response_serializer=wallet__pb2.SendShaAtomicSwapResponse.SerializeToString,
            ),
            'CreateBurnTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBurnTransaction,
                    request_deserializer=wallet__pb2.CreateBurnTransactionRequest.FromString,
                    response_serializer=wallet__pb2.CreateBurnTransactionResponse.SerializeToString,
            ),
            'ClaimShaAtomicSwapTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimShaAtomicSwapTransaction,
                    request_deserializer=wallet__pb2.ClaimShaAtomicSwapRequest.FromString,
                    response_serializer=wallet__pb2.ClaimShaAtomicSwapResponse.SerializeToString,
            ),
            'ClaimHtlcRefundTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimHtlcRefundTransaction,
                    request_deserializer=wallet__pb2.ClaimHtlcRefundRequest.FromString,
                    response_serializer=wallet__pb2.ClaimHtlcRefundResponse.SerializeToString,
            ),
            'CreateTemplateRegistration': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTemplateRegistration,
                    request_deserializer=wallet__pb2.CreateTemplateRegistrationRequest.FromString,
                    response_serializer=wallet__pb2.CreateTemplateRegistrationResponse.SerializeToString,
            ),
            'SetBaseNode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBaseNode,
                    request_deserializer=wallet__pb2.SetBaseNodeRequest.FromString,
                    response_serializer=wallet__pb2.SetBaseNodeResponse.SerializeToString,
            ),
            'StreamTransactionEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTransactionEvents,
                    request_deserializer=wallet__pb2.TransactionEventRequest.FromString,
                    response_serializer=wallet__pb2.TransactionEventResponse.SerializeToString,
            ),
            'RegisterValidatorNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterValidatorNode,
                    request_deserializer=wallet__pb2.RegisterValidatorNodeRequest.FromString,
                    response_serializer=wallet__pb2.RegisterValidatorNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tari.rpc.Wallet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tari.rpc.Wallet', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Wallet(object):
    """The gRPC interface for interacting with the wallet.
    Returns the current version of the running wallet service.

    This method retrieves the semantic version of the wallet software as defined in the Cargo.toml file (e.g., "1.2.3"). Useful for diagnostics and compatibility checks.

    Example usage (JavaScript gRPC client):
    ```javascript
    const response = await client.getVersion({});
    console.log(response.version); // e.g., "1.2.3"
    ```

    Example response:
    ```json
    {
    "version": "1.2.3"
    }
    ```
    """

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/GetVersion',
            wallet__pb2.GetVersionRequest.SerializeToString,
            wallet__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/GetState',
            wallet__pb2.GetStateRequest.SerializeToString,
            wallet__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckConnectivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/CheckConnectivity',
            wallet__pb2.GetConnectivityRequest.SerializeToString,
            wallet__pb2.CheckConnectivityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckForUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/CheckForUpdates',
            types__pb2.Empty.SerializeToString,
            network__pb2.SoftwareUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Identify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/Identify',
            network__pb2.GetIdentityRequest.SerializeToString,
            network__pb2.GetIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/GetAddress',
            types__pb2.Empty.SerializeToString,
            wallet__pb2.GetAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaymentIdAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/GetPaymentIdAddress',
            wallet__pb2.GetPaymentIdAddressRequest.SerializeToString,
            wallet__pb2.GetCompleteAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCompleteAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/GetCompleteAddress',
            types__pb2.Empty.SerializeToString,
            wallet__pb2.GetCompleteAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/Transfer',
            wallet__pb2.TransferRequest.SerializeToString,
            wallet__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/GetTransactionInfo',
            wallet__pb2.GetTransactionInfoRequest.SerializeToString,
            wallet__pb2.GetTransactionInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCompletedTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tari.rpc.Wallet/GetCompletedTransactions',
            wallet__pb2.GetCompletedTransactionsRequest.SerializeToString,
            wallet__pb2.GetCompletedTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/GetBalance',
            wallet__pb2.GetBalanceRequest.SerializeToString,
            wallet__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnspentAmounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/GetUnspentAmounts',
            types__pb2.Empty.SerializeToString,
            wallet__pb2.GetUnspentAmountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CoinSplit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/CoinSplit',
            wallet__pb2.CoinSplitRequest.SerializeToString,
            wallet__pb2.CoinSplitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportUtxos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/ImportUtxos',
            wallet__pb2.ImportUtxosRequest.SerializeToString,
            wallet__pb2.ImportUtxosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNetworkStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/GetNetworkStatus',
            types__pb2.Empty.SerializeToString,
            network__pb2.NetworkStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConnectedPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/ListConnectedPeers',
            types__pb2.Empty.SerializeToString,
            network__pb2.ListConnectedPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/CancelTransaction',
            wallet__pb2.CancelTransactionRequest.SerializeToString,
            wallet__pb2.CancelTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevalidateAllTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/RevalidateAllTransactions',
            wallet__pb2.RevalidateRequest.SerializeToString,
            wallet__pb2.RevalidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateAllTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/ValidateAllTransactions',
            wallet__pb2.ValidateRequest.SerializeToString,
            wallet__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendShaAtomicSwapTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/SendShaAtomicSwapTransaction',
            wallet__pb2.SendShaAtomicSwapRequest.SerializeToString,
            wallet__pb2.SendShaAtomicSwapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBurnTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/CreateBurnTransaction',
            wallet__pb2.CreateBurnTransactionRequest.SerializeToString,
            wallet__pb2.CreateBurnTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimShaAtomicSwapTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/ClaimShaAtomicSwapTransaction',
            wallet__pb2.ClaimShaAtomicSwapRequest.SerializeToString,
            wallet__pb2.ClaimShaAtomicSwapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimHtlcRefundTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/ClaimHtlcRefundTransaction',
            wallet__pb2.ClaimHtlcRefundRequest.SerializeToString,
            wallet__pb2.ClaimHtlcRefundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTemplateRegistration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/CreateTemplateRegistration',
            wallet__pb2.CreateTemplateRegistrationRequest.SerializeToString,
            wallet__pb2.CreateTemplateRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBaseNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/SetBaseNode',
            wallet__pb2.SetBaseNodeRequest.SerializeToString,
            wallet__pb2.SetBaseNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTransactionEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tari.rpc.Wallet/StreamTransactionEvents',
            wallet__pb2.TransactionEventRequest.SerializeToString,
            wallet__pb2.TransactionEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterValidatorNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tari.rpc.Wallet/RegisterValidatorNode',
            wallet__pb2.RegisterValidatorNodeRequest.SerializeToString,
            wallet__pb2.RegisterValidatorNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
